Implement new component create script + test

diff --git a/push b/push
--- a/push
+++ b/push
@@ -1,6 +1,29 @@
 #!/bin/bash
-read -p "Commit message: " desc
+
+# Style constants
+RED='\033[0;31m'
+RESET='\033[0m'
+
+# Check if correct number of inputs
+if [ "$#" -ne 1 ]; then
+    echo -e "${RED}Usage: ./push <COMMIT_MSG>.${RESET}"
+    exit 1
+fi
+
+# Check if in correct directory
+if [ "${PWD##*/}" != "Personal-Portfolio" ]; then
+    echo -e "${RED}Script must be executed in the root directory.${RESET}"
+    exit 1
+fi
+
+# Check if script test passes
+./src/tests/new/new_test > /dev/null
+if [ $? -eq 1 ]; then
+    echo -e "${RED}Bash script test failed.${RESET}"
+    exit 1
+fi
+
 npx prettier --write .
 git add -A && \
-git commit -m "$desc" && \
+git commit -m "$1" && \
 git push
